fixing syntax issue
Signed-off-by: Kai Huang <ahkcs@amazon.com>

diff --git a/.github/workflows/snapshot-publish.yml b/.github/workflows/snapshot-publish.yml
--- a/.github/workflows/snapshot-publish.yml
+++ b/.github/workflows/snapshot-publish.yml
@@ -109,63 +109,61 @@ jobs:
           
             TEMP_DIR=$(mktemp -d)
           
-            # Create version-specific metadata file
+            # Create version-specific metadata file without using heredoc
             echo "Creating version metadata file with commit ID"
-            cat > "${TEMP_DIR}/version-metadata.xml" << EOF
-  <?xml version="1.0" encoding="UTF-8"?>
-  <metadata>
-  <groupId>org.opensearch</groupId>
-  <artifactId>${PROJECT}</artifactId>
-  <version>${VERSION}</version>
-  <versioning>
-  <commitId>${COMMIT_ID}</commitId>
-  <snapshot>
-  <timestamp>${TIMESTAMP}</timestamp>
-  <buildNumber>1</buildNumber>
-  </snapshot>
-  <lastUpdated>${TIMESTAMP}</lastUpdated>
-  </versioning>
-  </metadata>
-  EOF
-  
-  # Upload version-specific metadata
-  VERSION_URL="https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/${PROJECT}/${VERSION}/maven-metadata.xml"
-  echo "Uploading version metadata to ${VERSION_URL}"
-  curl -v -u "${SONATYPE_USERNAME}:${SONATYPE_PASSWORD}" --upload-file "${TEMP_DIR}/version-metadata.xml" "${VERSION_URL}"
-  
-  # Download parent metadata
-  PARENT_URL="https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/${PROJECT}/maven-metadata.xml"
-  echo "Downloading parent metadata from ${PARENT_URL}"
-  curl -s -u "${SONATYPE_USERNAME}:${SONATYPE_PASSWORD}" -o "${TEMP_DIR}/maven-metadata.xml" "${PARENT_URL}"
-  
-  # Update parent metadata
-  echo "Updating parent metadata"
-  
-  # Check if current version exists in the versions list
-  if ! xmlstarlet sel -t -v "/metadata/versioning/versions/version[text()='${VERSION}']" "${TEMP_DIR}/maven-metadata.xml" | grep -q "${VERSION}"; then
-  echo "Adding new version ${VERSION} to versions list"
-  xmlstarlet ed -L -s "/metadata/versioning/versions" -t elem -n "version" -v "${VERSION}" "${TEMP_DIR}/maven-metadata.xml"
-  fi
-  
-  # Update latest
-  xmlstarlet ed -L -u "/metadata/versioning/latest" -v "${VERSION}" "${TEMP_DIR}/maven-metadata.xml"
-  
-  # Update lastUpdated
-  xmlstarlet ed -L -u "/metadata/versioning/lastUpdated" -v "${TIMESTAMP}" "${TEMP_DIR}/maven-metadata.xml"
-  
-  # Add commitId if it doesn't exist
-  if xmlstarlet sel -t -v "count(/metadata/versioning/commitId)" "${TEMP_DIR}/maven-metadata.xml" | grep -q "0"; then
-  echo "Adding commitId to parent metadata"
-  xmlstarlet ed -L -s "/metadata/versioning" -t elem -n "commitId" -v "${COMMIT_ID}" "${TEMP_DIR}/maven-metadata.xml"
-  else
-  echo "Updating commitId in parent metadata"
-  xmlstarlet ed -L -u "/metadata/versioning/commitId" -v "${COMMIT_ID}" "${TEMP_DIR}/maven-metadata.xml"
-  fi
-  
-  # Upload parent metadata
-  echo "Uploading updated parent metadata to ${PARENT_URL}"
-  curl -v -u "${SONATYPE_USERNAME}:${SONATYPE_PASSWORD}" --upload-file "${TEMP_DIR}/maven-metadata.xml" "${PARENT_URL}"
-  
-  # Clean up
-  rm -rf "${TEMP_DIR}"
-  done
+            echo '<?xml version="1.0" encoding="UTF-8"?>' > "${TEMP_DIR}/version-metadata.xml"
+            echo '<metadata>' >> "${TEMP_DIR}/version-metadata.xml"
+            echo "  <groupId>org.opensearch</groupId>" >> "${TEMP_DIR}/version-metadata.xml"
+            echo "  <artifactId>${PROJECT}</artifactId>" >> "${TEMP_DIR}/version-metadata.xml"
+            echo "  <version>${VERSION}</version>" >> "${TEMP_DIR}/version-metadata.xml"
+            echo "  <versioning>" >> "${TEMP_DIR}/version-metadata.xml"
+            echo "    <commitId>${COMMIT_ID}</commitId>" >> "${TEMP_DIR}/version-metadata.xml"
+            echo "    <snapshot>" >> "${TEMP_DIR}/version-metadata.xml"
+            echo "      <timestamp>${TIMESTAMP}</timestamp>" >> "${TEMP_DIR}/version-metadata.xml"
+            echo "      <buildNumber>1</buildNumber>" >> "${TEMP_DIR}/version-metadata.xml"
+            echo "    </snapshot>" >> "${TEMP_DIR}/version-metadata.xml"
+            echo "    <lastUpdated>${TIMESTAMP}</lastUpdated>" >> "${TEMP_DIR}/version-metadata.xml"
+            echo "  </versioning>" >> "${TEMP_DIR}/version-metadata.xml"
+            echo '</metadata>' >> "${TEMP_DIR}/version-metadata.xml"
+          
+            # Upload version-specific metadata
+            VERSION_URL="https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/${PROJECT}/${VERSION}/maven-metadata.xml"
+            echo "Uploading version metadata to ${VERSION_URL}"
+            curl -v -u "${SONATYPE_USERNAME}:${SONATYPE_PASSWORD}" --upload-file "${TEMP_DIR}/version-metadata.xml" "${VERSION_URL}"
+          
+            # Download parent metadata
+            PARENT_URL="https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/${PROJECT}/maven-metadata.xml"
+            echo "Downloading parent metadata from ${PARENT_URL}"
+            curl -s -u "${SONATYPE_USERNAME}:${SONATYPE_PASSWORD}" -o "${TEMP_DIR}/maven-metadata.xml" "${PARENT_URL}"
+          
+            # Update parent metadata
+            echo "Updating parent metadata"
+          
+            # Check if current version exists in the versions list
+            if ! xmlstarlet sel -t -v "/metadata/versioning/versions/version[text()='${VERSION}']" "${TEMP_DIR}/maven-metadata.xml" | grep -q "${VERSION}"; then
+              echo "Adding new version ${VERSION} to versions list"
+              xmlstarlet ed -L -s "/metadata/versioning/versions" -t elem -n "version" -v "${VERSION}" "${TEMP_DIR}/maven-metadata.xml"
+            fi
+          
+            # Update latest
+            xmlstarlet ed -L -u "/metadata/versioning/latest" -v "${VERSION}" "${TEMP_DIR}/maven-metadata.xml"
+          
+            # Update lastUpdated
+            xmlstarlet ed -L -u "/metadata/versioning/lastUpdated" -v "${TIMESTAMP}" "${TEMP_DIR}/maven-metadata.xml"
+          
+            # Add commitId if it doesn't exist
+            if xmlstarlet sel -t -v "count(/metadata/versioning/commitId)" "${TEMP_DIR}/maven-metadata.xml" | grep -q "0"; then
+              echo "Adding commitId to parent metadata"
+              xmlstarlet ed -L -s "/metadata/versioning" -t elem -n "commitId" -v "${COMMIT_ID}" "${TEMP_DIR}/maven-metadata.xml"
+            else
+              echo "Updating commitId in parent metadata"
+              xmlstarlet ed -L -u "/metadata/versioning/commitId" -v "${COMMIT_ID}" "${TEMP_DIR}/maven-metadata.xml"
+            fi
+          
+            # Upload parent metadata
+            echo "Uploading updated parent metadata to ${PARENT_URL}"
+            curl -v -u "${SONATYPE_USERNAME}:${SONATYPE_PASSWORD}" --upload-file "${TEMP_DIR}/maven-metadata.xml" "${PARENT_URL}"
+          
+            # Clean up
+            rm -rf "${TEMP_DIR}"
+          done
